#!/bin/bash
	
#PBS -N CASSCF
#PBS -o pbs.out
#PBS -e pbs.err
#PBS -l walltime=01:59:00
#PBS -l mem=12gb
#PBS -m be -M joachim.scheerlinck@ugent.be
#PBS -l nodes=1:ppn=1
#PBS -A 2025_026

ulimit -s unlimited

#Note that the workdir should be the one used by autoCAS, but not the autoCAS folder itself as to not overwrite data
#While the fileorb should directly be used from the autocas final folder, to ensure the chosen autocas active space is used
export MOLCAS_WORKDIR=/dodrio/scratch/projects/starting_2025_097/molcas_workdirs/casscf_singlet_speedup/
mkdir -p $MOLCAS_WORKDIR
export MOLCAS_PRINT=verbose
export MOLCAS_MOLDEN=ON
export MOLCAS_MEM=20000
export MOLCAS_NPROCS=1
export OMP_NUM_THREADS=1

cd ${PBS_O_WORKDIR}

module load autoCAS
module load vsc-mympirun

pymolcas -np $MOLCAS_NPROCS Po2casscf.input -f
